### ISSUE TITLE
No redirect after verifyEmail

### ISSUE THREAD

**Issue by ajbarry** [meteor-useraccounts/core#173]
Hey @splendido, I have the following configuration (using v1.3.2) but rather than redirecting to '/dashboard' after the verifyEmail link is processed, I get the message: `Verify email link expired`
The user is successfully logged-in but they need to use other navigation in the template to navigate to `/dashboard` or away from the `/verify-email/<token>` page. Do you have any ideas what I am missing?

```coffeescript
AccountsTemplates.configure
  enablePasswordChange: true
  enforceEmailVerification: true
  sendVerificationEmail: true
  showForgotPasswordLink: true

AccountsTemplates.configureRoute('signUp')

AccountsTemplates.configureRoute('verifyEmail', {
  redirect: '/dashboard'
})

AccountsTemplates.configureRoute('signIn', {
  redirect: '/dashboard'
})

AccountsTemplates.configureRoute('changePwd')
AccountsTemplates.configureRoute('forgotPwd')
AccountsTemplates.configureRoute('resetPwd')
```

**Comment by timothyarmes** [comment]
Hi,

I was also experiencing this issue. It's taken me a while to track it down, but having found it I suspect that many of us are going to trip over it.

What's happening is that the verify route's onAfterAction is being called twice, and the second time it submit's the same code again. In my case that was happening because I have a waitOn on my global RouteController which subscribes to the current user. The onAfterAction is called once before the subscription is ready, and once more afterwards.

This is how I fixed it:

    Router.configure
       waitOn: ->
          if Meteor.userId() and @route.getName() isnt 'atVerifyEmail'
             return [ Meteor.subscribe('userInfo', [ Meteor.userId() ]) ]

I wonder if UserAccounts can be altered to avoid this situation automatically? If not, this is worth mentioning in the docs.

**Comment by splendido** [comment]
Hi @timothyarmes,
thanks for your deep jump into AT code.

Do you think we should switch to the `onRun` hook?
From the [hooks docs](https://github.com/EventedMind/iron-router/blob/devel/Guide.md#available-hook-methods) it seems it is supposed to be run only once.

**Comment by ajbarry** [comment]
I have a bit of new info. I stumbled on to an apparent workaround for my situation.

I inverted the rules I used in my ```AccountsTemplates.ensureSignedIn``` config. I experienced this issue when I was using the ```except:[]``` clause. After switching around to use the ```only:[]``` clause to protect just the pages that required login the verification redirect started working for me.

I hope this helps rather than further burry the root cause but it worked for me.

**Comment by splendido** [comment]
This should be now solved thanks to 70d6efb7c11a161547069eff01a0ca5adeda166f

**Comment by almogdesign** [comment]
@splendido  having the issue I just tested 70d6efb which did not fix it, If I remove the onRun it works. It's just not running. 

I also tested @timothyarmes waitOn config which did not help. I have the same waitOn setup and I tested @ajbarry change from expect to only which also did not fix the issue.
